program: /data/sinopec/xjtu/zfh/Advanced_ML_Coursework/evaluate.py
project: Camouflaged_Object_Analysis_Test
method: grid
parameters:
  dataset:
    values: ["CAMO", "COD10K"]
  model:
    values: ["DeepLab", "DLabCRF"]


command:
  - ${env}
  - torchrun
  - --nproc_per_node
  - 6
  - ${program}
  - --config
  - /data/sinopec/xjtu/zfh/Advanced_ML_Coursework/configs/camouflage.yaml
  - --distributed
  - ${args}